version: 2
updates:
- package-ecosystem: "npm"
  directories:
    - "/netlify/functions"
    - "/"
  schedule:
    interval: "weekly"
- package-ecosystem: "bundler"
  directory: "/"
  schedule:
    interval: "weekly"
