#SITE CONFIGURATION

title: Andrew Stiefel
tagline: '@andrewstiefel'
description: I'm a digital strategist and creative copywriter who builds trust and connection between brands and the people they serve.
url: 'https://andrewstiefel.com'
baseurl: ""

# BUILD SETTINGS

markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-archives

sass:
  sass_dir: _sass
  style: compressed

collections:
  projects:
    output: true
    permalink: '/projects/:title/'
    sort_by: order

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: taxonomy
  permalinks:
    tag: '/writing/tag/:name/'
    category: '/writing/category/:name/'

breadcrumbs:
  root:
    hide: true
    image: false

paginate: 10
paginate_path: '/writing/page:num/'

permalink: '/writing/:title/'

# CONTACT

author:
  name: Andrew Stiefel
  url: 'https://andrewstiefel.com'
  email: andrew@andrewstiefel.com
  twitter: andrewstiefel
  linkedin: andrewstiefel
  medium: andrewstiefel
  github: andrewstiefel
