#SITE CONFIGURATION

title: Andrew Stiefel
description: 
repository: "andrewstiefel/music-portfolio"
baseurl: 
url: "http://andrewstiefel.com"

google_tag_manager: GTM-P7PZFVP

# SEO PLUGIN

social:
  name: Andrew Stiefel
  links:
    - https://www.facebook.com/andrewstiefel
    - https://twitter.com/andrewstiefel
    - https://www.instagram.com/andrewstiefel
    - https://www.youtube.com/user/andrewstiefel
    - https://www.linkedin.com/in/andrewstiefel
    - https://github.com/andrewstiefel
    
#THEME SETTINGS

navigation: # Navigation links
  - {name: 'Music', link: '/music'}
  - {name: 'Recordings', link: '/recordings'}
  - {name: 'Contact', link: '/contact'}
  
email: andrew@andrewstiefel.com
twitter_username: andrewstiefel
github_username: andrewstiefel
instagram_username: andrewstiefel
facebook_username: andrewstiefel
linkedin_username: andrewstiefel

#BUILD SETTINGS

markdown: kramdown
include: ['_pages']
permalink: /blog/:title

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

compress_html:
  clippings: all

plugins: 
  - jekyll-sitemap
  - jekyll-seo-tag