### SITE SETTINGS
title: Andrew Stiefel
tagline: '@andrewstiefel'
description: Hey, I'm Andrew Stiefel. Welcome to my digital garden, a slowly growing collection of ideas in the form of working notes and narrative essays.
url: "https://andrewstiefel.com"
timezone: America/Los_Angeles

### SITE AUTHOR
author:
  name: Andrew Stiefel
  url: 'https://andrewstiefel.com'
  email: andrew@andrewstiefel.com
  twitter: andrewstiefel
  linkedin: andrewstiefel
  mastodon: 'https://mas.to/@andrewstiefel'
  bluesky: 'https://bsky.app/profile/andrewstiefel.bsky.social'
  medium: andrewstiefel
  github: andrewstiefel

### BUILD SETTINGS
plugins:
  - jekyll-archives
  - jekyll-last-modified-at
  - jekyll-sitemap
  - jekyll-target-blank
  - jekyll-tailwindcss
  - jekyll-tidy
markdown: kramdown
highlighter: none
include: [_pages]
permalink: '/:title/'
tailwind:
  version: 3.4.13

defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts

### JEKYLL ARCHIVE SETTINGS
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-category
    tag: archive-tag
  permalinks:
    category: '/:name/'
    tag: '/tag/:name/'

### JEKYLL TIDY SETTINGS
jekyll_tidy:
  exclude: ["feed.xml", "assets/js/bundle.js"]

### OPEN GRAPH IMAGE SETTTINGS
ogImageBackground: '/assets/img/og-background.png'
cloudinary_cloud: andrewstiefel

exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.babel.js
  - LICENSE.md
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - tailwind.config.js
  - netlify.toml