#SITE CONFIGURATION

title: Andrew Stiefel
tagline: '@andrewstiefel'
description: 'Social and Digital Media Strategist in Seattle, Washington'
url: "https://andrewstiefel.com"
baseurl: ""

# BUILD SETTINGS

markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

sass:
  sass_dir: _sass
  style: compressed

collections:
  projects:
    output: true
    permalink: /projects/:title/
    sort_by: order

breadcrumbs:
  root:
    hide: true
    image: false

paginate: 5
paginate_path: "/blog/page:num/"

permalink: /blog/:title/

# SEO SETTINGS

social:
  name: Andrew Stiefel
  links:
    - https://twitter.com/andrewstiefel
    - https://www.linkedin.com/in/andrewstiefel
    - https://github.com/andrewstiefel

twitter:
  username: andrewstiefel
  card: summary_large_image

# CONTACT

author:
  name: Andrew Stiefel
  url: https://andrewstiefel.com
  email: andrew@andrewstiefel.com
  twitter: andrewstiefel
  linkedin: andrewstiefel
  github: andrewstiefel
