### SITE CONFIGURATION

title: Andrew Stiefel
tagline: '@andrewstiefel'
description: Hey, I'm Andrew Stiefel. Welcome to my digital garden, a slowly growing collection of ideas in the form of working notes and finished essays.
url: 'https://andrewstiefel.com'
baseurl: ""

### BUILD SETTINGS

include: [_pages]
markdown: kramdown

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-archives
  - jekyll-seo-tag
  - jekyll-last-modified-at
  - jekyll-tidy

sass:
  sass_dir: _sass
  style: compressed

permalink: '/:title/'

### JEKYLL ARCHIVE SETTINGS

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: taxonomy
  permalinks:
    tag: '/topic/:name/'
    category: '/:name/'

### JEKYLL FEED SETTINGS

feed:
  categories:
    - essays
    - notes

### JEKYLL SEO SETTINGS

twitter:
  username: andrewstiefel
  card: summary_large_image

social:
  name: Andrew Stiefel
  links:
    - https://twitter.com/andrewstiefel
    - https://www.linkedin.com/in/andrewstiefel
    - https://github.com/andrewstiefel

### JEKYLL LAST MODIFIED SETTINGS

last-modified-at:
    date-format: '%-d %b %Y'

### SITE AUTHOR

author:
  name: Andrew Stiefel
  url: 'https://andrewstiefel.com'
  email: andrew@andrewstiefel.com
  twitter: andrewstiefel
  linkedin: andrewstiefel
  medium: andrewstiefel
  github: andrewstiefel


### DEFAULTS

defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts
