#SITE CONFIGURATION

title: Andrew Stiefel
tagline: '@andrewstiefel'
description: 'Social Media and Content Strategist working in Seattle. Find me online @andrewstiefel.'
url: 
baseurl: https://andrewstiefel.github.io
paginate: 5
paginate_path: "/blog/page:num/"

# PERMALINKS

permalink: /blog/:title

# CONTACT

author:
  name: Andrew Stiefel
  url: https://www.andrewstiefel.com
  email: andrew@andrewstiefel.com
  twitter: https://twitter.com/andrewstiefel
  linkedin: https://www.linkedin.com/in/andrewstiefel
  github: https://github.com/andrewstiefel