title: Andrew Stiefel
tagline: '@andrewstiefel'
description: Hey, I'm Andrew Stiefel. Welcome to my digital garden, a slowly growing collection of ideas in the form of working notes and narrative essays.

include: [_pages]
permalink: '/:title/'

plugins:
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-tidy

### JEKYLL ARCHIVE SETTINGS

jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-category
    tag: archive-tag
  permalinks:
    category: '/:name/'
    tag: '/tag/:name/'

### JEKYLL TIDY SETTINGS

jekyll_tidy:
  exclude: ["feed.xml"]

exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.babel.js
  - LICENSE.md
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - src
  - tailwind.config.js
  - netlify.toml
