#SITE CONFIGURATION

title: Andrew Stiefel
tagline: '@andrewstiefel'
description: Writes about thing, thing, and thing.
url: 'https://andrewstiefel.com'
baseurl: ""

# BUILD SETTINGS

markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-archives

sass:
  sass_dir: _sass
  style: compressed

permalink: '/:title/'

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: taxonomy
  permalinks:
    tag: '/tag/:name/'
    category: '/category/:name/'

# CONTACT

author:
  name: Andrew Stiefel
  url: 'https://andrewstiefel.com'
  email: andrew@andrewstiefel.com
  twitter: andrewstiefel
  linkedin: andrewstiefel
  medium: andrewstiefel
  github: andrewstiefel
