#SITE CONFIGURATION

title: Andrew Stiefel
tagline: '@andrewstiefel'
description: 'Hello, I&#39;m Andrew. I&#39;m a social media and content strategist living and working in Seattle.'
url: https://andrewstiefel.com
baseurl: ""

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-time-to-read

#PAGINATE

paginate: 5
paginate_path: "/blog/page:num/"

# PERMALINKS

permalink: /blog/:title

# CONTACT

author:
  name: Andrew Stiefel
  url: https://www.andrewstiefel.com
  email: andrew@andrewstiefel.com
  twitter: https://twitter.com/andrewstiefel
  linkedin: https://www.linkedin.com/in/andrewstiefel
  github: https://github.com/andrewstiefel
