#SITE CONFIGURATION

title: Andrew Stiefel
tagline: '@andrewstiefel'
description: Hey, I'm Andrew Stiefel. I write about creativity and strategy and publish a semi-weekly newsletter called Margin Notes.
url: 'https://andrewstiefel.com'
baseurl: ""

# BUILD SETTINGS

markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-archives

sass:
  sass_dir: _sass
  style: compressed

permalink: '/blog/:title/'

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: taxonomy
  permalinks:
    tag: '/blog/tag/:name/'
    category: '/blog/category/:name/'

# CONTACT

author:
  name: Andrew Stiefel
  url: 'https://andrewstiefel.com'
  email: andrew@andrewstiefel.com
  twitter: andrewstiefel
  linkedin: andrewstiefel
  medium: andrewstiefel
  github: andrewstiefel
