### CATEGORIES
guides:
  description: |
    Practical writing that explains how to do something

essays:
  description: |
    Narrative writing with a distinct point of view

notes:
  description: |
    Short-form writing that connects sources and asks questions