### CATEGORIES
articles:
  description: |
    Mostly objective writing exploring a single topic or idea

essays:
  description: |
    Narrative writing with a distinct point of view

notes:
  description: |
    Short-form writing that connects sources and asks questions