server {
    listen 80;
    server_name _;

    include /etc/nginx/conf.d/origin-token.conf;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ $uri.html =404;
    }
}